name: Basic CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - '*'  # Trigger on PRs to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Use Java 11
          distribution: 'temurin'
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Cache Maven packages
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the project
      
      - name: Run tests
        run: mvn test  # Run the unit tests

      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses default GitHub token
          workdir: "."  # Assuming Checkstyle should run from the root directory
          level: "warning"  # Set Checkstyle reporting level
          reporter: "github-pr-check"  # Display results in PRs
          filter_mode: "added"  # Only comments on changes
          fail_on_error: "false"  # Continue even if Checkstyle finds issues
          checkstyle_config: "google_checks.xml"  # Use Google coding conventions
          checkstyle_version: "10.3.4"  # Specify Checkstyle version

  codeql-analysis:
    runs-on: ubuntu-latest  # Use Ubuntu for the CodeQL job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java  # Specify languages for analysis

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the project for CodeQL analysis

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
