name: Basic CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the project for CodeQL analysis

      - name: List compiled classes
        run: ls -R target/classes  # List compiled classes to ensure they're available

      - name: Run tests
        run: mvn test

      - name: Checkstyle for Java
        uses: dbelyaev/action-checkstyle@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: "."
          level: "warning"
          reporter: "github-pr-check"
          filter_mode: "added"
          fail_on_error: "false"
          checkstyle_config: "google_checks.xml"
          checkstyle_version: "10.3.4"

  codeql-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the project for CodeQL analysis

      - name: List compiled classes
        run: ls -R target/classes  # List compiled classes to ensure they're available

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
